name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.0, 10.0, 11.0, 12.0]
        exclude:
          - php: 8.3
            laravel: 9.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_sqlite, intl
          coverage: xdebug

      - name: Install Laravel Testbench
        run: |
          if [ "${{ matrix.laravel }}" = "9.0" ]; then
            composer require "orchestra/testbench:^7.0" --dev --no-interaction --no-update
          elif [ "${{ matrix.laravel }}" = "10.0" ]; then
            composer require "orchestra/testbench:^8.0" --dev --no-interaction --no-update
          elif [ "${{ matrix.laravel }}" = "11.0" ]; then
            composer require "orchestra/testbench:^9.0" --dev --no-interaction --no-update
          elif [ "${{ matrix.laravel }}" = "12.0" ]; then
            composer require "orchestra/testbench:^10.0" --dev --no-interaction --no-update
          fi

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPUnit Tests with Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text

      - name: Verify coverage file exists
        run: |
          if [ ! -f coverage.xml ]; then
            echo "Error: coverage.xml file was not generated"
            exit 1
          fi
          echo "Coverage file size: $(wc -c < coverage.xml) bytes"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_sqlite

      - run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse


  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring

      - run: composer install --prefer-dist --no-interaction

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
