name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        exclude:
          - php: 8.3
            laravel: 9.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_sqlite, intl

      - name: Install Laravel Testbench version
        run: |
          composer require "orchestra/testbench:^${{ matrix.laravel }}" --dev --no-interaction --no-update

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit

  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_sqlite

      - run: composer install --prefer-dist --no-interaction
      - run: composer phpstan

  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring

      - run: composer install --prefer-dist --no-interaction
      - run: composer pint-test
