name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*, 12.*]
        exclude:
          - php: 8.0
            laravel: 10.*
          - php: 8.0
            laravel: 11.*
          - php: 8.0
            laravel: 12.*
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*
          - php: 8.3
            laravel: 9.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo_sqlite
          coverage: xdebug

      - name: Install correct Laravel/Testbench version
        run: |
          composer remove laravel/framework orchestra/testbench --dev --no-interaction || true
          composer require "orchestra/testbench:^${{ matrix.laravel }}" --dev --no-interaction --update-with-dependencies

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Tests with Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text

      - name: Verify coverage file exists
        run: |
          if [ ! -f coverage.xml ]; then
            echo "Error: coverage.xml file was not generated"
            exit 1
          fi
          echo "Coverage file size: $(wc -c < coverage.xml) bytes"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Analysis

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_sqlite

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: composer phpstan

  pint:
    runs-on: ubuntu-latest
    name: Laravel Pint

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_sqlite

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Laravel Pint
        run: composer pint-test
